import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './redux/Providers'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Chatterhub',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id='photo-picker-element'></div>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
